#:schema node_modules/wrangler/config-schema.json
name = "studio3"
compatibility_date = "2025-01-10"
compatibility_flags = ["nodejs_compat"]

# For Cloudflare Pages deployment
pages_build_output_dir = ".next"

[env.production]
name = "studio3-production"

[env.staging]
name = "studio3-staging"

# Environment variables will be set through Cloudflare dashboard
# or wrangler secret commands for sensitive data